cloudflare/wirefilter

- .travis.yml
- Cargo.lock
- engine/src/types.rs
- ffi/Cargo.toml
- ffi/include/wirefilter.h
- ffi/src/lib.rs
- ffi/tests/ctests/Cargo.toml
- ffi/tests/ctests/build.rs
- ffi/tests/ctests/src/lib.rs
- ffi/tests/ctests/src/tests.c
This new crate is here to provide a set of C based tests that will
serve two purposes:
* Provide some examples how to use the FFI bindings
* Test that those bindings are actually working as intended
Internally, it relies on ffi-ctests/ctests/tests.c file which contains
tests written in C and that is compiled at cargo configuration time
through the use of a build.rs file. This produces a wirefilter_ffi_ctests.so
shared library that is later used in the ffi-ctests/ctests/src/lib.rs file
to call the different tests functions. All of this is done in order to try
to integrate somehow properly with cargo test.
> FW-1087: provide wirefilter.h C header file and add ffi-ctests crate

- engine/benches/bench.rs
These take forever and many don't measure the performance of function execution, but rather performance of other operators.
Let's reduce them only to isolated cases.
> Reduce benchmarking matrix for functions

- Cargo.lock
- engine/Cargo.toml
- ffi/Cargo.toml
Upstream regex has recently fixed a bunch of issues which could previously lead to panics (mostly in the parser).
There has also been lots of work on performance in the meanwhile for both compilation (our "parsing") and execution. Some interesting benchmark changes:
-
```
parsing/http.user_agent ~ "(?i)googlebot/\d+\.\d+"
time:   [124.27 us 124.67 us 125.09 us]
change: [-38.917% -38.443% -37.977%] (p = 0.00 < 0.05)
Performance has improved.
```
-
```
parsing/http.user_agent ~ "Googlebot"
time:   [28.030 us 28.439 us 28.921 us]
change: [-13.106% -11.929% -10.718%] (p = 0.00 < 0.05)
Performance has improved.
```
-
```
execution/http.user_agent ~ "(?i)googlebot/\d+\.\d+"/"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...
time:   [67.045 ns 67.248 ns 67.470 ns]
change: [+21.247% +21.880% …
```
> Upgrade regex

- engine/benches/bench.rs
- engine/examples/cli.rs
- engine/src/ast/field_expr.rs
- engine/src/ast/function_expr.rs
- engine/src/functions.rs
- engine/src/lex.rs
- engine/src/lib.rs
This makes naming of these concepts more consistent with other languages, makes it easier to distinguish between the definition site and the call site, and frees up names like `FunctionArg` for other usages.
> Rename "arg" in definitions to "param" 

- engine/README.md
It used to show an arbitrary latest build, but we're interested only in master branch.
> Update Travis badge to show master

- engine/src/ast/function_expr.rs
- engine/src/execution_context.rs
- engine/src/lex.rs
- engine/src/lib.rs
- engine/src/types.rs
See commit messages for details.
In particular, this in combination with #14 should allow to more easily `.unwrap()` on owned arguments instead of handling type mismatches manually.
> Implement TryFrom on LhsValue and unify type mismatch errors

- engine/benches/bench.rs
- engine/src/ast/combined_expr.rs
- engine/src/ast/field_expr.rs
- engine/src/ast/function_expr.rs
- engine/src/ast/index_expr.rs
- engine/src/ast/mod.rs
- engine/src/ast/simple_expr.rs
- engine/src/execution_context.rs
- engine/src/lex.rs
- engine/src/lib.rs
- engine/src/rhs_types/map.rs
- engine/src/rhs_types/mod.rs
- engine/src/scheme.rs
- engine/src/types.rs
- ffi/include/wirefilter.h
- ffi/src/lib.rs
- ffi/src/transfer_types/ownership_repr/rust_box.rs
- ffi/tests/ctests/src/lib.rs
- ffi/tests/ctests/src/tests.c
This patch series introduce a new `Map` data type. It is useful to describe named data that are only known at execution time.
`Type` is not copy-able anymore because the new `Type::Map` variant holds `Box<Type>` to describe the type of values stored in the map. Keys are always expected to be regular strings.
A new `Map` structure has been defined that holds a `Type` and a `HashMap<LhsValue>`, type checking is done at filter parsing and data insertion time.
`FieldIndex` is an enum that describe how to access an element from an `LhsValue`. It currently only has one `MapKey` variant to access an element of a map but can be improved in the future to handle `ArrayIndex` when the array data type will be introduced.
On the syntax side, map element can be accessed using the classic [] operator: …
> Introduce map data type

- engine/src/types.rs
* add `value_type()` method in order to get the `Type` of the values contained in an `Array` (same was done for `Map` for coherence)
* implement `IntoIterator` trait to be able to iterate over the values contained in an `Array`
> Improve array type

- engine/src/ast/function_expr.rs
- engine/src/execution_context.rs
- engine/src/lib.rs
- engine/src/types.rs
This was deleted when working on the Map & Array data types.
See e500dc1f5f80c38273d2436f9fe82cff7fef3c40 for more info.
> Re-add TryFrom implementation to LhsValue

- Cargo.lock
- engine/Cargo.toml
- engine/src/ast/field_expr.rs
- engine/src/ast/function_expr.rs
- engine/src/functions.rs
- engine/src/lex.rs
- engine/src/scheme.rs
This RFC is meant to introduce generic functions. Generic functions are functions whose prototype is not entirely known in advance but instead depends of the argument itself. This includes:
* variadic functions, like `concat`
* function that can accept different argument type but where arguments have constraints between each other
* when arrays will be introduced, functions that can accept array of any type.
This proposal relies on a newly introduced `FunctionDefinition` trait who provides an abstract interface to validate and execute function calls.
On a side note, function argument parsing have been modified. Each argument is blindly parsed then passed to the trait in order to validate it.
Parsing is now done is this order for each argument:
* try to parse a field or a nested function …
> Introduce generic functions

- engine/src/lex.rs
- engine/src/lib.rs
Export `lex::LexErrorKind` to crate for assertions in tests.
> Export lex::LexErrorKind to crate

- engine/src/lhs_types/array.rs
- engine/src/lib.rs
- engine/src/types.rs
This is needed to be able to construct more advanced types, such as arrays and maps, using the public API.
Also make the `CompoundType::from_type` function publicly so it is possible to construct compound types in public functions using the public API.
> Expose `CompoundType` publicly

- engine/src/ast/field_expr.rs
- engine/src/ast/index_expr.rs
Other cases are already inline so this makes the code more consistent and easier to reason about.
> Inline `IdentifierExpr::compile_with_compiler` in `IndexExpr::compile_with_compiler`

- engine/src/ast/field_expr.rs
- engine/src/ast/function_expr.rs
- engine/src/ast/parse.rs
- engine/src/functions.rs
- engine/src/lib.rs
- engine/src/rhs_types/regex/imp_real.rs
- engine/src/rhs_types/wildcard.rs
- engine/src/scheme.rs
Passing the whole parser allows to access too many things, like the scheme and potentially other things we might add in the future. It also makes writing unit tests more cumbersome since we now have to build a scheme first just to get a dummy parser.
> Only pass parser settings when checking function parameters.

- engine/benches/bench.rs
- engine/examples/cli.rs
- engine/src/ast/field_expr.rs
- engine/src/ast/function_expr.rs
- engine/src/ast/index_expr.rs
- engine/src/ast/logical_expr.rs
- engine/src/ast/visitor.rs
- engine/src/execution_context.rs
- engine/src/filter.rs
- engine/src/lib.rs
- engine/src/rhs_types/regex/mod.rs
- engine/src/rhs_types/wildcard.rs
- engine/src/scheme.rs
- ffi/cbindgen.toml
- ffi/include/wirefilter.h
- ffi/src/lib.rs
- ffi/tests/ctests/src/lib.rs
- ffi/tests/ctests/src/tests.c
This makes the scheme immutable and allows to tailor its internals for parsing and execution of filter expressions.
Extracted from https://github.com/cloudflare/wirefilter/pull/119
> Introduce `SchemeBuilder` to build a `Scheme`

- engine/src/execution_context.rs
Extracted from https://github.com/cloudflare/wirefilter/pull/119
> Add helpers to manipulate execution context without references to the scheme

- engine/src/ast/field_expr.rs
- engine/src/ast/function_expr.rs
- engine/src/ast/index_expr.rs
- engine/src/ast/logical_expr.rs
- engine/src/ast/mod.rs
- engine/src/ast/parse.rs
- engine/src/ast/visitor.rs
- engine/src/compiler.rs
- engine/src/execution_context.rs
- engine/src/filter.rs
- engine/src/functions/all.rs
- engine/src/functions/any.rs
- engine/src/functions/concat.rs
- engine/src/functions/mod.rs
- engine/src/lib.rs
- engine/src/scheme.rs
- ffi/src/lib.rs
This allows to remove the `'s` lifetime in most of the codebase which should also simplify the life of wirefilter users.
It also enables downstream crates to implement deserialization of filter AST with serde using TLS stored scheme or similar tricks.
> Use reference counted scheme instead of references

- engine/src/scheme.rs
- ffi/tests/ctests/src/tests.c
This change is a necessary rework of scheme serialization to allow for additional field properties that will be introduced in a future commit.
Before this change, a serialized scheme was a map of field name to field type. After this change, a serialized scheme is a map of field name to field definition object, which only contain its type for now but can be extended with additional properties.
> Rework `Scheme` serialization

- engine/README.md
- engine/src/lib.rs
- the .build() call is required to align with recent rework of serialization
- 'Type' was unused
I, mtovino@cloudflare.com, am both a rust n00b and a wirefilter n00b.  I tried building the example so that I could tinker and learn, and needed to make these changes for the example to build and lint.
> update README example to match current implementation

- engine/src/rhs_types/regex/imp_real.rs
Benchmarks have shown that disabling onepass doesn't impact matching performance but speeds-up regex building and should also reduce memory usage.
> Disable regex onepass DFA
